

CREATE TABLE IF NOT EXISTS public.cities
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    city_name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.routes
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    departure_city_id bigint NOT NULL,
    arrival_city_id bigint NOT NULL,
    user_ticket_price integer NOT NULL,
    departure_time timestamp with time zone NOT NULL,
    arrival_time timestamp with time zone NOT NULL,
    baggage_ticket_price integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    login character varying NOT NULL,
    password character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users_roles
(
    user_id bigint,
    user_role character varying
);

CREATE TABLE IF NOT EXISTS public.tickets
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    passanger_id bigint NOT NULL,
    route_id bigint NOT NULL,
    departure_id bigint NOT NULL,
    arrival_id bigint NOT NULL,
    ticket_status character varying NOT NULL,
    seat_number character varying NOT NULL,
    date_of_selling timestamp without time zone NOT NULL,
    pricer double precision NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.routes_cities
(
    route_id bigint NOT NULL,
    city_id bigint,
    CONSTRAINT route_id_city_id_unique_constraint UNIQUE (route_id, city_id)
);

ALTER TABLE IF EXISTS public.routes
    ADD CONSTRAINT departure_city_id_foreign_key_constraint FOREIGN KEY (departure_city_id)
        REFERENCES public.cities (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.routes
    ADD CONSTRAINT arrival_city_id_foreign_key_constraint FOREIGN KEY (arrival_city_id)
        REFERENCES public.cities (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.users_roles
    ADD CONSTRAINT user_id_foreign_key_constraint FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.tickets
    ADD CONSTRAINT arrival_id_fkey_constraint FOREIGN KEY (arrival_id)
        REFERENCES public.cities (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.tickets
    ADD CONSTRAINT departure_id_fkey_constraint FOREIGN KEY (departure_id)
        REFERENCES public.cities (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.tickets
    ADD CONSTRAINT route_id_fkey_constraint FOREIGN KEY (route_id)
        REFERENCES public.routes (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.routes_cities
    ADD CONSTRAINT route_id_fkey_constraint FOREIGN KEY (route_id)
        REFERENCES public.routes (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.routes_cities
    ADD CONSTRAINT city_id_fkey_constraint FOREIGN KEY (city_id)
        REFERENCES public.cities (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;
